version: '3.3'

services:

  client:
    container_name: client
    restart: always
    env_file: ./.docker/.env
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: ["yarn","start"]
