version: '3.3'

services:

  client:
    container_name: client
    restart: always
    env_file: ./.docker/.env
    ports:
      - "8080:8080"
    volumes:
      - /workspace/node_modules
      - /workspace/.next
      - ./:/workspace
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    command: ["yarn","start"]
