version: '3.3'

services:

  client: &client
    container_name: client
    restart: always
    env_file: ./.docker/.env
    ports:
      - "8080:8080"
    volumes:
      - /workspace/node_modules
      - /workspace/.next
      - ./:/workspace
    build:
      context: .
      dockerfile: ./.docker/dev.Dockerfile
    command: ["yarn","dev"]

  storybook:
    <<: *client
    container_name: storybook
    ports:
      - "6006:6006"
    command: ["yarn","storybook"]
