name: Type check
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          node-version: '16.x'
      - name: install
        run : yarn install
      - name: type-check
        run : yarn type:check
